# Generated by Django 4.2.3 on 2024-03-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_type', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room_type.roomtype'),
        ),
    ]
