# Generated by Django 4.2.3 on 2024-03-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_amenity_name_alter_hotel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
