# Generated by Django 4.2.3 on 2024-03-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], max_length=20)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
