# Generated by Django 4.2.3 on 2024-03-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_number',
            new_name='room_type',
        ),
    ]
